#
# Makefile for the linux yaffs/yaffs2 filesystem routines.
#

O_TARGET := yaffs2.o

obj-y  := yaffs_mtdif.o yaffs_mtdif2.o yaffs_ecc.o yaffs_fs.o yaffs_guts.o yaffs_packedtags2.o yaffs_tagscompat.o yaffs_tagsvalidity.o
obj-m  := $(O_TARGET)

include $(TOPDIR)/Rules.make
