/*
 *  linux/include/asm-arm/arch-mmsp2/irq.h
 *
 *  Copyright (c) 2004 MIZI Research, Inc. All rights reserved.
 *
 *  2004-04-02  Janghoon Lyu
 *              - created.
 *
 * (C) Copyright 2004
 * DIGNSYS Inc. < www.dignsys.com >
 * Kane Ahn < hbahn@dignsys.com >
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef _ASM_ARCH_IRQS_H
#define _ASM_ARCH_IRQS_H

#define IRQ_DUMMY		0x0000ffff
#define IRQ_CHAIN_MASK		0xffff0000
#define IRQ_CHAIN_OFS		16

/* 한 그룹 당 최대 16개의 인터럽터 가능. 메인은 예외 */
#define IRQ_GRP_MAX_IRQ		(16)
#define IRQ_GRP_MASK		(0xf)

#define IRQ_GRP_MAIN0		(0 << IRQ_CHAIN_OFS)
#define IRQ_GRP_MAIN1		(1 << IRQ_CHAIN_OFS)
#define IRQ_GRP_TIMER		(2 << IRQ_CHAIN_OFS)
#define IRQ_GRP_UART		(3 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOA		(4 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOB		(5 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOC		(6 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOD		(7 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOE		(8 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOF		(9 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOG		(10 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOH		(11 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOI		(12 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOJ		(13 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOK		(14 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOL		(15 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOM		(16 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPION		(17 << IRQ_CHAIN_OFS)
#define IRQ_GRP_GPIOO		(18 << IRQ_CHAIN_OFS)
#define IRQ_GRP_DMA		(19 << IRQ_CHAIN_OFS)

#define IRQ_GEN_OFS(x)		(IRQ_GRP_MAX_IRQ * ((x) >> IRQ_GRP_MAX_IRQ))

#define GRP_OFS(x)	((x) >> IRQ_CHAIN_OFS)
#define GRP_NUM(x)	((x) / IRQ_GRP_MAX_IRQ)

#define NR_IRQS			(IRQ_GRP_MAX_IRQ*20)

#define IRQ_DISP		0	/* Display controller */
#define IRQ_IMGH		1	/* Image capture controller (HSYNC) */
#define IRQ_IMGV		2	/* Image capture controller (VSYNC) */
#define IRQ_TIMER		5	/* Timer */
#define IRQ_MSTICK		6	/* Memory stick */
#define IRQ_SSP			7	/* SSP */
#define IRQ_PPM			8	/* PPM */
#define IRQ_DMA			9	/* DMA */
#define IRQ_UART		10	/* UART 0/1/2/3 */
#define IRQ_GRP2D		11	/* 2D graphic controller */
#define IRQ_SCALER		12	/* Image scaler */
#define IRQ_USBH		13	/* USB Host */
#define IRQ_SD			14	/* MMC/SD */
#define IRQ_USBD		15	/* USB device */
#define IRQ_RTC			16	/* RTC */
#define IRQ_ADC			17	/* ADC */
#define IRQ_IIC			18	/* IIC */
#define IRQ_AC97		19	/* AC97 */
#define IRQ_IRDA		20	/* IrDA */
#define IRQ_GPIO		23	/* GPIO */
#define IRQ_CDROM		24	/* CDROM */
#define IRQ_OWM			25	/* One wire master */
#define IRQ_DUALCPU		26	/* Dual CPU */
#define IRQ_MCUC		27	/* Non DRAM Memory controller */
#define IRQ_VLD			28	/* VLD */
#define IRQ_VIDEO		29	/* Video processor */
#define IRQ_MPEGIF		30	/* MPEG Interface */
#define IRQ_IIS			31	/* IIS controller */

#define IRQ_TIMER0		(0 + IRQ_GEN_OFS(IRQ_GRP_TIMER))
#define IRQ_TIMER1		(1 + IRQ_GEN_OFS(IRQ_GRP_TIMER)) 
#define IRQ_TIMER2		(2 + IRQ_GEN_OFS(IRQ_GRP_TIMER)) 
#define IRQ_TIMER3		(3 + IRQ_GEN_OFS(IRQ_GRP_TIMER)) 

#define IRQ_TXD0		(0 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_RXD0		(1 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_ERROR0		(2 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_MODEM0		(3 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_TXD1		(4 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_RXD1		(5 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_ERROR1		(6 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_MODEM1		(7 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_TXD2		(8 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_RXD2		(9 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_ERROR2		(10 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_MODEM2		(11 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_TXD3		(12 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_RXD3		(13 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_ERROR3		(14 + IRQ_GEN_OFS(IRQ_GRP_UART))
#define IRQ_MODEM3		(15 + IRQ_GEN_OFS(IRQ_GRP_UART))

#define IRQ_GPIO_A0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))
#define IRQ_GPIO_A15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOA))

#define IRQ_GPIO_B0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))
#define IRQ_GPIO_B15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOB))

#define IRQ_GPIO_C0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))
#define IRQ_GPIO_C15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOC))

#define IRQ_GPIO_D0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))
#define IRQ_GPIO_D15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOD))

#define IRQ_GPIO_E0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))
#define IRQ_GPIO_E15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOE))

#define IRQ_GPIO_F0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))
#define IRQ_GPIO_F15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOF))

#define IRQ_GPIO_G0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))
#define IRQ_GPIO_G15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOG))

#define IRQ_GPIO_H0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))
#define IRQ_GPIO_H15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOH))

#define IRQ_GPIO_I0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))
#define IRQ_GPIO_I15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOI))

#define IRQ_GPIO_J0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))
#define IRQ_GPIO_J15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOJ))

#define IRQ_GPIO_K0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))
#define IRQ_GPIO_K15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOK))

#define IRQ_GPIO_L0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))
#define IRQ_GPIO_L15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOL))

#define IRQ_GPIO_M0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))
#define IRQ_GPIO_M15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOM))

#define IRQ_GPIO_N0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPION))
#define IRQ_GPIO_N15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPION))

#define IRQ_GPIO_O0		(0 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O1		(1 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O2		(2 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O3		(3 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O4		(4 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O5		(5 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O6		(6 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O7		(7 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O8		(8 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O9		(9 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O10		(10 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O11		(11 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O12		(12 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O13		(13 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O14		(14 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))
#define IRQ_GPIO_O15		(15 + IRQ_GEN_OFS(IRQ_GRP_GPIOO))

#define IRQ_DMA0		(0 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA1		(1 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA2		(2 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA3		(3 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA4		(4 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA5		(5 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA6		(6 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA7		(7 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA8		(8 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA9		(9 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA10		(10 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA11		(11 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA12		(12 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA13		(13 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA14		(14 + IRQ_GEN_OFS(IRQ_GRP_DMA))
#define IRQ_DMA15		(15 + IRQ_GEN_OFS(IRQ_GRP_DMA))

#endif /* _ASM_ARCH_IRQS_H */
