/* Open2x Project - NAND Flashing Software (ARM-ELF for JTAG)
 * Copyright (C) 2006 The Open2x project
 *
 * Based on GPL'ed BIN2H.C - Author Unknown
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 *
 * $URL$
 * $Id$
 *
 */

#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>

#define FILE_MAX_LEN	0x30

void error(char *error_str)
{
	printf("%s\n", error_str);
	exit(0);
}

void usage(void)
{
	printf("Usage : ./bin2h <binary file name> <header file name>\n");
	exit(1);
}

int main( int argc, char *argv[] )
{
	int i;
	char infile[FILE_MAX_LEN], outfile[FILE_MAX_LEN];
	FILE *in, *out;
	int f_start, f_end, f_size;
	unsigned char data;
	unsigned char *header[7] = {
		"/*\n",
		" * This was automaticly generated by bin2h.\n",
		" * Do NOT edit.\n",
		" */\n",
		"\n",
		"/* Bios Image buffer */\n",
		"unsigned char biosbuf[] = {"};

	if(argc < 3)    usage();

	strcpy(infile, argv[1]);
	strcpy(outfile, argv[2]);
	if( (out = fopen(outfile, "wb")) == NULL ) {
		error("Error, can not create binary output file\n");
		exit(1);
	}

	for(i=0; i<7; i++) fprintf(out, "%s", header[i]);

	if( (in = fopen(infile, "rb")) == NULL ) {
		error("Error, can not open binary input file\n");
		exit(1);
	}

	fseek(in, 0L, SEEK_END);
	f_end = ftell(in);
	fseek(in, 0L, SEEK_SET);
	f_start = ftell(in);
	f_size = f_end - f_start;

	for(i=0; i<f_size; i++) {
		fread(&data,sizeof(data),1,in);
		if(!(i&0xf)) fprintf(out, "\n");
		if(i==(f_size-1))
			fprintf(out, "0x%02x", data);
		else
			fprintf(out, "0x%02x, ", data);
	}
	data = '}';
	fwrite(&data, sizeof(data), 1, out);
	data = ';';
	fwrite(&data, sizeof(data), 1, out);
	data = '\n';
	fwrite(&data, sizeof(data), 1, out);
	fclose(in);
	fclose(out);
//	printf("Done!\n");

	exit(0);
}
