/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* Protect against multiple inclusion */
#ifndef MPLAYER_CONFIG_H
#    define MPLAYER_CONFIG_H 1

/* use GNU internationalization */
//#    define USE_I18N 1
#    undef USE_I18N

/* missing mmap function on libc5 systems */
#    ifndef MAP_FAILED
#        define MAP_FAILED     ((void *) -1)
#    endif

/* use setlocale() function */
#    define USE_SETLOCALE 1

/* Runtime CPU detection */
#    undef RUNTIME_CPUDETECT

/* Dynamic a/v plugins */
#    undef DYNAMIC_PLUGINS

/* "restrict" keyword */
#    define restrict __restrict

/* __builtin_expect branch prediction hint */
#    undef HAVE_BUILTIN_EXPECT

/* attribute(used) as needed by some compilers */
#    if (__GNUC__ * 100 + __GNUC_MINOR__ >= 300)
#        define attribute_used __attribute__((used))
#    else
#        define attribute_used
#    endif

#    define PREFIX "/usr/local"

#    define USE_OSD 1
#    define USE_SUB 1

/* enable/disable SIGHANDLER */
#    define ENABLE_SIGHANDLER 1

/* enable/disable automatic gdb attach on crash, requires SIGHANDLER */
#    undef CRASH_DEBUG

/* Toggles debugging informations */
#    undef MP_DEBUG

/* Indicates that Ogle's libdvdread is available for DVD playback */
#    undef USE_DVDREAD

/* Indicates that dvdread is from libmpdvdkit */
#    undef USE_MPDVDKIT

/* Additional options for libmpdvdkit*/
#    undef DVD_STRUCT_IN_DVD_H
#    define DVD_STRUCT_IN_LINUX_CDROM_H 1
#    undef DVD_STRUCT_IN_SYS_CDIO_H
#    undef DVD_STRUCT_IN_SYS_DVDIO_H
#    undef DVD_STRUCT_IN_BSDI_DVDIOCTL_DVD_H




#    undef SOLARIS_USCSI
#    undef HPUX_SCTL_IO
#    define HAVE_STDDEF_H 1

/* Common data directory (for fonts, etc) */
#    define MPLAYER_DATADIR "/usr/local/share/mplayer"
#    define MPLAYER_CONFDIR "/etc/mplayer"
#    define MPLAYER_LIBDIR "/usr/local/lib"

/* Define this to compile stream-caching support, it can be enabled via
   -cache <kilobytes> */
#    undef USE_STREAM_CACHE

/* Define to include support for XviD/Divx4Linux/OpenDivx */
#    undef USE_DIVX

/* Define to use the new XviD/DivX4Linux library instead of open source OpenDivX */
/* You have to change DECORE_LIBS in config.mak, too! */
#    undef NEW_DECORE

/* Define if you are using DivX5Linux Decore library */
#    undef DECORE_DIVX5

/* Define if you are using XviD library */
#    undef HAVE_XVID3
#    undef HAVE_XVID4
#    undef DECORE_XVID
#    undef ENCORE_XVID

/* Define if you are using the X.264 library */
#    undef HAVE_X264

/* Define to include support for libdv-0.9.5 */
#    undef HAVE_LIBDV095

/* If build mencoder */
#    undef HAVE_MENCODER

/* Indicates if XviD/Divx4linux encore is available
   Note: for mencoder */


/* Indicates if libmp3lame is available
   Note: for mencoder */



/* Define libmp1e for realtime mpeg encoding (for DXR3 and DVB cards) */
#    undef USE_MP1E

/* Define this to enable avg. byte/sec-based AVI sync method by default:
   (use -bps or -nobps commandline option for run-time method selection)
   -bps gives better sync for vbr mp3 audio, it is now default */
#    define AVI_SYNC_BPS 1

/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
#    define USE_FAKE_MONO 1

/* Undefine this if your sound card driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
#    define HAVE_AUDIO_SELECT 1

/* define this to use iconv(3) function to codepage conversions */
#    define USE_ICONV 1

/* define this to use nl_langinfo function */
#    define USE_LANGINFO 1

/* define this to use RTC (/dev/rtc) for video timers (LINUX only) */
#    undef HAVE_RTC

/* set up max. outburst. use 65536 for ALSA 0.5, for others 16384 is enough */
#     define MAX_OUTBURST 65536

/* set up audio OUTBURST. Do not change this! */
#    define OUTBURST 512

/* Define this if your system has the header file for the OSS sound interface */
#    define HAVE_SYS_SOUNDCARD_H 1

/* Define this if your system has the header file for the OSS sound interface
 * in /usr/include */
#    undef HAVE_SOUNDCARD_H

/* Define this if your system has the sysinfo header */
#    define HAVE_SYS_SYSINFO_H 1

/* Define this if your system has ftello() */

#    define HAVE_FTELLO 1
#    ifndef HAVE_FTELLO
/* Need these for FILE and off_t an config.h is usually before other includes*/
#        include <stdio.h>
#        include <sys/types.h>
off_t           ftello(FILE *);
#    endif

/* Define this if your system has the "malloc.h" header file */
#    define HAVE_MALLOC_H 1

/* memalign is mapped to malloc if unsupported */
#    define HAVE_MEMALIGN 1
#    ifndef HAVE_MEMALIGN
#        define memalign(a,b) malloc(b)
#        define MEMALIGN_HACK 1
#    endif

/* Define this if your system has the "alloca.h" header file */
#    define HAVE_ALLOCA_H 1

/* Define this if your system has the "sys/mman.h" header file */
#    define HAVE_SYS_MMAN_H 1

/* Define this if you have the elf dynamic linker -ldl library */
#    define HAVE_LIBDL 1

/* Define this if you have the kstat kernel statistics library */
#    undef HAVE_LIBKSTAT

/* Define this if you have zlib */
#    define HAVE_ZLIB 1
#    ifdef HAVE_ZLIB
#        define CONFIG_ZLIB 1
#    endif

/* Define this if you have shm support */
#    define HAVE_SHM 1

/* Define this if your system has scandir & alphasort */
#    define HAVE_SCANDIR 1

/* Define this if your system has strsep */
#    define HAVE_STRSEP 1

/* Define this if your system has strlcpy */
#    undef HAVE_STRLCPY
#    ifndef HAVE_STRLCPY
//unsigned int    strlcpy(char *dest, char *src, unsigned int size);
#    endif

/* Define this if your system has strlcat */
#    undef HAVE_STRLCAT
#    ifndef HAVE_STRLCAT
//unsigned int    strlcat(char *dest, char *src, unsigned int size);
#    endif

/* Define this if your system has fseeko */
#    define HAVE_FSEEKO 1
#    ifndef HAVE_FSEEKO
/* Need these for FILE and off_t an config.h is usually before other includes*/
#        include <stdio.h>
#        include <sys/types.h>
int             fseeko(FILE *, off_t, int);
#    endif

#    define HAVE_LOCALTIME_R 1

/* Define this if your system has vsscanf */
#    define HAVE_VSSCANF 1

/* Define this if your system has swab */
#    define HAVE_SWAB 1

/* Define this if your system has no posix select */
#    undef HAVE_NO_POSIX_SELECT

/* Define this if your system has gettimeofday */
#    define HAVE_GETTIMEOFDAY 1

/* Define this if your system has glob */
#    define HAVE_GLOB 1

/* Define this if your system has pthreads */
#    undef HAVE_PTHREADS

/* LIRC (remote control, see www.lirc.org) support: */
#    undef HAVE_LIRC

/*
 * LIRCCD (LIRC client daemon)
 * See http://www.dolda2000.cjb.net/~fredrik/lirccd/
 */
#    undef HAVE_LIRCC

/* DVD navigation support using libdvdnav */



/* Define this to enable MPEG 1/2 image postprocessing (requires a FAST CPU!) */
#    define MPEG12_POSTPROC 1

/* Define this to enable image postprocessing in libavcodec (requires a FAST CPU!) */
#    define FF_POSTPROCESS 1

/* Define to include support for OpenDivx postprocessing */
#    undef HAVE_ODIVX_POSTPROCESS

/* Win32 DLL support */
#    undef USE_WIN32DLL
#    define WIN32_PATH ""

/* DirectShow support */
#    undef USE_DIRECTSHOW

/* Mac OS X specific features */

#    undef MACOSX_FINDER_SUPPORT

/* Build our Win32-loader */


/* ffmpeg's libavcodec support (requires libavcodec source) */
#    undef USE_LIBAVCODEC
#    undef USE_LIBAVCODEC_SO

/* ffmpeg's libavformat support (requires libavformat source) */
#    undef USE_LIBAVFORMAT
#    undef CONFIG_WIN32

/* risky codecs */
#    define CONFIG_RISKY 1

/* Use libavcodec's decoders */
#    define CONFIG_DECODERS 1
/* Use libavcodec's encoders */
#    define CONFIG_ENCODERS 1

#    define CONFIG_MPEGAUDIO_HP 1

/* Use codec libs included in mplayer CVS / source dist: */
#    define USE_MP3LIB 1
#    define USE_LIBA52 1
#    undef CONFIG_DTS
#    define USE_LIBMPEG2 1

/* Use libfame encoder filter */
#    undef USE_LIBFAME

/* XAnim DLL support */
#    undef USE_XANIM
/* Default search path */
#    undef XACODEC_PATH

/* RealPlayer DLL support */
#    undef USE_REALCODECS
/* Default search path */
#    undef REALCODEC_PATH

/* LIVE.COM Streaming Media library support */
#    undef STREAMING_LIVE_DOT_COM

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#    undef USE_FASTMEMCPY

/* Use unrarlib for Vobsubs */
#    define USE_UNRARLIB 1

/* gui support, please do not edit this option */
#    undef HAVE_NEW_GUI

/* Audio output drivers */
#    define USE_OSS_AUDIO 1
#    define PATH_DEV_DSP "/dev/dsp"
#    define PATH_DEV_MIXER "/dev/mixer"
#    undef HAVE_ALSA5
#    undef HAVE_ALSA9
#    undef HAVE_ALSA1X

#    undef USE_ESD
#    undef HAVE_ESD_LATENCY
#    undef USE_POLYP

#    undef HAVE_SYS_ASOUNDLIB_H
#    undef HAVE_ALSA_ASOUNDLIB_H
#    undef USE_SUN_AUDIO
#    undef USE_SGI_AUDIO
#    undef HAVE_WIN32WAVEOUT
#    undef HAVE_NAS

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#    undef FAST_OSD
#    undef FAST_OSD_TABLE

/* Enable TV Interface support */
#    undef USE_TV

/* Enable EDL support */
#    define USE_EDL

/* Enable Video 4 Linux TV interface support */
#    undef HAVE_TV_V4L

/* Enable Video 4 Linux 2 TV interface support */
#    undef HAVE_TV_V4L2

/* Enable *BSD BrookTree TV interface support */
#    undef HAVE_TV_BSDBT848

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#    undef WORDS_BIGENDIAN

#    define ARCH_ARMV4L 1

/* libmpeg2 wants ARCH_PPC and the rest of mplayer use ARCH_POWERPC,
 * define ARCH_PPC if ARCH_POWERPC is set to cope with that.
 */
#    ifdef ARCH_POWERPC
#        define ARCH_PPC 1
#    endif

/* the same issue as with ARCH_POWERPC but with ffmpeg/libavcodec */
#    ifdef ARCH_ARMV4L
#        define ARCH_ARM 1
#    endif

/* only gcc3 can compile mvi instructions */


/* Define this for Cygwin build for win32 */


/* Define this to any prefered value from 386 up to infinity with step 100 */
#    define __CPU__ arm

#    undef MP_WORDSIZE

#    define TARGET_LINUX 1

#    define HAVE_VCD 1

#    ifdef sun
#        define	DEFAULT_CDROM_DEVICE	"/vol/dev/aliases/cdrom0"
#        define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#    elif defined(HPUX)
#        define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#        define DEFAULT_DVD_DEVICE     "/dev/dvd"
#    elif defined(WIN32)
#        define DEFAULT_CDROM_DEVICE    "D:"
#        define DEFAULT_DVD_DEVICE	"D:"
#    elif defined(SYS_DARWIN)
#        define DEFAULT_CDROM_DEVICE    "/dev/disk1"
#        define DEFAULT_DVD_DEVICE	"/dev/rdiskN"
#    elif defined(__OpenBSD__)
#        define DEFAULT_CDROM_DEVICE	"/dev/rcd0a"
#        define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#    else
#        define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#        define DEFAULT_DVD_DEVICE	"/dev/dvd"
#    endif


/*----------------------------------------------------------------------------
**
** NOTE: Instead of modifying these definitions here, use the
**       --enable/--disable options of the ./configure script!
**       See ./configure --help for details.
**
*---------------------------------------------------------------------------*/

/* C99 lrintf function available */
#    define HAVE_LRINTF 1

/* yes, we have inttypes.h */
#    define HAVE_INTTYPES_H 1

/* int_fastXY_t emulation */


/* nanosleep support */
#    define HAVE_NANOSLEEP 1

/* SMB support */
#    undef LIBSMBCLIENT

/* termcap flag for getch2.c */
#    undef USE_TERMCAP

/* termios flag for getch2.c */
#    define HAVE_TERMIOS 1
#    undef HAVE_TERMIOS_H
#    define HAVE_SYS_TERMIOS_H 1

/* enable PNG support */
#    undef HAVE_PNG

/* enable JPEG support */
#    undef HAVE_JPEG

/* enable PNM support */
#    define HAVE_PNM

/* enable md5sum support */
#    define HAVE_MD5SUM

/* enable GIF support */
#    undef HAVE_GIF
#    undef HAVE_GIF_4


/* enable FreeType support */
#    undef HAVE_FREETYPE

/* enable Fontconfig support */
#    undef HAVE_FONTCONFIG

/* liblzo support */
#    undef USE_LIBLZO

/* libmad support */
#    define USE_LIBMAD 1

/* enable OggVorbis support */
//senquack - why is this enabled? Ogg cannot be embedded in Avi files and that is all we support:
//#    define HAVE_OGGVORBIS 1
#undef HAVE_OGGVORBIS

/* enable Tremor as vorbis decoder */
//senquack - why is this enabled? Ogg cannot be embedded in Avi files and that is all we support:
//#    define TREMOR 1
#undef TREMOR

/* enable OggTheora support */
#    undef HAVE_OGGTHEORA

/* enable Matroska support */
#    undef HAVE_MATROSKA

/* enable FAAD (AAC) support */
#    define HAVE_FAAD 1
#    define USE_INTERNAL_FAAD 1
#    define FAADVERSION 12



    /*
     * enable network 
     */
#        define MPLAYER_NETWORK 1

    /*
     * enable ftp support 
     */
#        define HAVE_FTP 1



/* enable winsock2 instead of Unix functions*/
#    undef HAVE_WINSOCK2

/* define this to use inet_aton() instead of inet_pton() */
#    undef USE_ATON

/* enables / disables cdparanoia support */
#    undef HAVE_CDDA

/* enables / disables VIDIX usage */
#    undef CONFIG_VIDIX

/* enables / disables new input joystick support */
#    undef HAVE_JOYSTICK

/* enables / disables QTX codecs */
#    undef USE_QTX_CODECS

/* enables / disables osd menu */
#    undef HAVE_MENU

/* enables / disables subtitles sorting */
#    define USE_SORTSUB 1

/* XMMS input plugin support */
#    undef HAVE_XMMS
#    define XMMS_INPUT_PLUGIN_DIR ""

/* enables inet6 support */
#    define HAVE_AF_INET6 1

/* do we have gethostbyname2? */
#    define HAVE_GETHOSTBYNAME2 1

/* Extension defines */
#    undef HAVE_3DNOW           // only define if you have 3DNOW (AMD k6-2, AMD Athlon, iDT WinChip, etc.)
#    undef HAVE_3DNOWEX         // only define if you have 3DNOWEX (AMD Athlon, etc.)
#    undef HAVE_MMX             // only define if you have MMX (newer x86 chips, not P54C/PPro)
#    undef HAVE_MMX2            // only define if you have MMX2 (Athlon/PIII/4/CelII)
#    undef HAVE_SSE             // only define if you have SSE (Intel Pentium III/4 or Celeron II)
#    undef HAVE_SSE2            // only define if you have SSE2 (Intel Pentium 4)
    // only define if you have Altivec (G4)

    // enables usage of altivec.h


#    undef HAVE_MLIB            // Sun mediaLib, available only on solaris
    // only define if you have VIS ( ultrasparc )

/* libmpeg2 uses a different feature test macro for mediaLib */
#    ifdef HAVE_MLIB
#        define LIBMPEG2_MLIB 1
#    endif

/* libvo options */
#    define SCREEN_SIZE_X 1
#    define SCREEN_SIZE_Y 1
#    undef HAVE_X11
#    undef HAVE_XV
#    undef HAVE_XVMC
#    undef HAVE_XF86VM
#    undef HAVE_XINERAMA
#    undef HAVE_GL
#    undef GL_WIN32
#    undef HAVE_DGA
#    undef HAVE_DGA2
#    define HAVE_SDL 1
/* defined for SDLlib with keyrepeat bugs (before 1.2.1) */
#    undef BUGGY_SDL
#    undef HAVE_DIRECTX
#    undef HAVE_GGI
#    undef HAVE_3DFX
#    undef HAVE_TDFXFB
#    undef HAVE_TDFX_VID
#    undef HAVE_DIRECTFB

#    undef HAVE_ZR
#    undef HAVE_BL
#    undef HAVE_MGA
#    undef HAVE_XMGA

#    define HAVE_FBDEV 1
#    undef HAVE_DXR2
#    undef HAVE_DXR3
#    undef HAVE_DVB
#    undef HAS_DVBIN_SUPPORT
#    undef HAVE_SVGALIB
#    undef HAVE_VESA
#    undef HAVE_XDPMS
#    undef HAVE_AA
#    undef HAVE_CACA
#    define HAVE_TGA 1
#    undef HAVE_TOOLAME

/* used by GUI: */


#    if defined(HAVE_GL) || defined(HAVE_X11) || defined(HAVE_XV)
#        define X11_FULLSCREEN 1
#    endif

#    if 0
//#define DEBUG
#        ifdef DEBUG
#            define dprintf(x...) printf(x)
#        else
#            define dprintf(x...)
#        endif
#    endif

#endif                          /* MPLAYER_CONFIG_H */
